/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "secondary": "#29657e",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#96ceea",
        "tertiary": "#4e616c",
        "inverse-primary": "#81d7b2",
        "tertiary-container": "#8699a5",
        "surface-bright": "#f8fafa",
        "surface-tint": "#006c4e",
        "outline-variant": "#bec9c1",
        "inverse-surface": "#2e3131",
        "on-primary-container": "#003726",
        "outline": "#6f7a73",
        "primary-fixed": "#9df4ce",
        "on-secondary-container": "#2a667e",
        "surface-container": "#eceeee",
        "on-primary-fixed": "#002115",
        "surface-container-high": "#e6e8e9",
        "secondary-container": "#a9e2ff",
        "error-container": "#ffdad6",
        "primary-container": "#50a684",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f2a",
        "surface-container-highest": "#e1e3e3",
        "surface": "#f8fafa",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f1",
        "on-tertiary-fixed": "#0a1e27",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#374953",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3f4943",
        "primary": "#006c4e",
        "on-tertiary": "#ffffff",
        "background": "#f8fafa",
        "surface-container-low": "#f2f4f4",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#d1e6f2",
        "on-primary-fixed-variant": "#00513a",
        "surface-dim": "#d8dada",
        "secondary-fixed": "#bfe9ff",
        "on-secondary-fixed-variant": "#024d65",
        "surface-variant": "#e1e3e3",
        "on-tertiary-container": "#1e313b",
        "primary-fixed-dim": "#81d7b2",
        "tertiary-fixed-dim": "#b5c9d6",
        "on-background": "#191c1d"
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      boxShadow: {
        'premium': '0px 4px 24px rgba(0, 0, 0, 0.04)',
      }
    },
  },
  plugins: [],
}
